# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: userdata.proto for package 'userdata.v1'

require 'grpc'
require 'userdata_pb'

module Userdata
  module V1
    module UserData
      # The Service to access Users Repository
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'userdata.v1.UserData'

        # Create a new user
        rpc :createUser, CreateUserRequest, User
        # Get the user by id or email
        rpc :getUser, GetUserRequest, User
        rpc :deleteUser, DeleteUserRequest, DeleteResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
