# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userdata.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "userdata.v1.DeleteUserRequest" do
    optional :id, :int32, 1
  end
  add_message "userdata.v1.DeleteResponse" do
    optional :status, :bool, 1
  end
  add_message "userdata.v1.CreateUserRequest" do
    optional :first_name, :string, 1
    optional :last_name, :string, 2
    optional :email, :string, 3
  end
  add_message "userdata.v1.GetUserRequest" do
    oneof :unique_user_oneof do
      optional :id, :int32, 1
      optional :email, :string, 2
    end
  end
  add_message "userdata.v1.User" do
    optional :id, :int32, 1
    optional :first_name, :string, 2
    optional :last_name, :string, 3
    optional :email, :string, 4
  end
end

module Userdata
  module V1
    DeleteUserRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("userdata.v1.DeleteUserRequest").msgclass
    DeleteResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("userdata.v1.DeleteResponse").msgclass
    CreateUserRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("userdata.v1.CreateUserRequest").msgclass
    GetUserRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("userdata.v1.GetUserRequest").msgclass
    User = Google::Protobuf::DescriptorPool.generated_pool.lookup("userdata.v1.User").msgclass
  end
end
